name: CI

on:
  push:
  pull_request:

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: preview

      - name: Restaurar dependências
        run: dotnet restore src/eshop-microservices.sln

      - name: Compilar solução
        run: dotnet build src/eshop-microservices.sln --no-restore

      - name: Executar testes
        run: dotnet test src/eshop-microservices.sln --no-build --no-restore